/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MsevcikAmbulanceWlList {
    }
}
declare global {
    interface HTMLMsevcikAmbulanceWlListElement extends Components.MsevcikAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLMsevcikAmbulanceWlListElement: {
        prototype: HTMLMsevcikAmbulanceWlListElement;
        new (): HTMLMsevcikAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "msevcik-ambulance-wl-list": HTMLMsevcikAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface MsevcikAmbulanceWlList {
    }
    interface IntrinsicElements {
        "msevcik-ambulance-wl-list": MsevcikAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "msevcik-ambulance-wl-list": LocalJSX.IntrinsicElements["msevcik-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLMsevcikAmbulanceWlListElement>;
        }
    }
}
