/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Cv2AmbulanceWlList {
    }
}
declare global {
    interface HTMLCv2AmbulanceWlListElement extends Components.Cv2AmbulanceWlList, HTMLStencilElement {
    }
    var HTMLCv2AmbulanceWlListElement: {
        prototype: HTMLCv2AmbulanceWlListElement;
        new (): HTMLCv2AmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "cv2-ambulance-wl-list": HTMLCv2AmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface Cv2AmbulanceWlList {
    }
    interface IntrinsicElements {
        "cv2-ambulance-wl-list": Cv2AmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cv2-ambulance-wl-list": LocalJSX.Cv2AmbulanceWlList & JSXBase.HTMLAttributes<HTMLCv2AmbulanceWlListElement>;
        }
    }
}
